### ISSUE TITLE
Actualizar a la versión actual de airbnb.

### ISSUE THREAD

**Issue by michaeljota** [paolocarrasco/javascript-style-guide#2]
Hola! Gracias por la traducción. Comparando las notas, han cambiado cosas allá que aquí no se ven reflejadas. No sé si es porque no las usas o quizás porque no lo has revisado.

En cualquier caso, no sé. Me parece bien tener la guía actualizada en español. 

Muchas gracias!

**Comment by paolocarrasco** [comment]
Hola Michael,

Sí, están diferentes porque la guía de AirBnB ahora se orienta principalmente a los estándares de ES2015, por eso he creado un [branch](https://github.com/paolocarrasco/javascript-style-guide/tree/es2015) donde estoy traduciendo esos últimos cambios. Todo lo que se refiere a ES5 sí está actualizado (fíjate que hay un fólder [ES5](https://github.com/airbnb/javascript/tree/master/es5) en el repo de AirBnB que sí está sincronizado con el master de este repo).

Como es un repo abierto, si deseas puedes apoyarme para sacar pronto la versión de ES2015.

Dejaré abierto este issue hasta hacer el merge del branch con el master.

Muchas gracias

**Comment by paolocarrasco** [comment]
@michaeljota ya están muchos de los nuevos cambios de la guía original. Voy a ir actualizando de a pocos las secciones que faltan.

**Comment by michaeljota** [comment]
¡Muchas gracias! Lo revisaré en casa. 👍
